/*
SELECT DISTINCT CITY
FROM STATION
WHERE 
RIGHT(CITY,1) NOT IN ('a','e','i','o','u')
OR
LEFT(CITY,1) NOT IN ('a','e','i','o','u');
*/
(
SELECT DISTINCT CITY
FROM STATION
WHERE  
CITY  NOT LIKE 'a%' AND
CITY NOT LIKE 'e%' AND
CITY NOT LIKE 'i%' AND
CITY NOT LIKE 'o%' AND
CITY NOT LIKE 'u%' )

UNION
(SELECT DISTINCT CITY
FROM STATION
WHERE
CITY NOT LIKE '%a' AND
CITY NOT LIKE '%e' AND
CITY NOT LIKE '%i' AND
CITY NOT LIKE '%o' AND
CITY NOT LIKE '%u'
);

